name: .NET Build and Test (PR)

on:
  pull_request:
    branches:
      - release
      - develop
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/dotnet.yml'
  workflow_dispatch:

jobs:
  pull-request-test:
    uses: ./.github/workflows/dotnet.yml
