name: .NET Build and Test (Push)

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/dotnet.yml'

jobs:
  push-test:
    uses: ./.github/workflows/dotnet.yml
