name: .NET Build and Test

on:
  workflow_call:

env:
  KUI_SOLUTION: HttpPostExperiment.sln
  KUI_SOLUTION_BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: Development
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dotnet Clean
        run: dotnet clean ${{ env.KUI_SOLUTION }}

      - name: Dotnet Restore
        run: dotnet restore ${{ env.KUI_SOLUTION }}

      - name: Dotnet Build
        run: dotnet build ${{ env.KUI_SOLUTION }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} --no-restore

      - name: Run Tests with Coverage
        run: dotnet test ${{ env.KUI_SOLUTION }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Code Coverage Summary Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/**/coverage.cobertura.xml
          repo_token: ${{ github.token }}
          minimum_coverage: 50
